Разметка главной страницы
htmlacademy-adaptive/98669-sedona-21 pull request #2
Opened 2020-11-15 22:26 UTC by Ranyar

2020-11-16 19:33 UTC, Shramkoweb requested changes

2020-11-16 19:33 UTC, Shramkoweb commented on source/index.html
> +              как на кнопке "Найти гостиницу" - похоже, что у них одинаковый внешний вид и поведение -->
А что в них одинакового?

2020-11-16 19:33 UTC, Shramkoweb commented on source/index.html
> +              <a href="#">Главная</a><!-- Думаю на пункты меню повесить класс button,
На главной убираем href="#" будучи на ней

2020-11-16 19:33 UTC, Shramkoweb commented on source/index.html
> +            <p class="reasons__title">Настоящий городок</p>
Это заголовок конкретного `reason` а не всего `reasons`

На li замиксуй новй блок `reasons__item reasons-item reasons-item--illustrated` и все внутри уже делай от этого нового блока.

Вот почитай https://yoksel.github.io/easy-markup/bem-rules/#elem-elem

2020-11-16 19:33 UTC, Shramkoweb commented on source/index.html
> +      <a class="contacts-map" href="">
Зачем тут новый блок?

2020-11-16 19:33 UTC, Shramkoweb commented on source/index.html
> +      <div class="page-footer__copyright">
Я думаю тут надо замиксовать copyright и внутри уже от него идти

2020-11-16 19:37 UTC, Ranyar commented on source/index.html
> +              как на кнопке "Найти гостиницу" - похоже, что у них одинаковый внешний вид и поведение -->
![2020-11-17_00-37-02](https://user-images.githubusercontent.com/14089426/99299455-0e378d00-286d-11eb-8278-debcfae614ed.png)
Мне так по стайлгайду показалось

2020-11-16 20:51 UTC, Shramkoweb commented on source/index.html
> +              как на кнопке "Найти гостиницу" - похоже, что у них одинаковый внешний вид и поведение -->
А в мобилке. Ок попробуй, хорошая идея. Я просто смотрел на десктоп)) Не нашел ничего общего 
👍

2020-11-17 03:17 UTC, Ranyar commented on source/index.html
> +              <a href="#">Главная</a><!-- Думаю на пункты меню повесить класс button,
Done

2020-11-17 03:23 UTC, Ranyar commented on source/index.html
> +            <p class="reasons__title">Настоящий городок</p>
Замиксовал, только в новом блоке порядок слов поменял как в примерах, чтобы не путать

2020-11-17 03:24 UTC, Ranyar commented on source/index.html
> +      <a class="contacts-map" href="">
Поправил

2020-11-17 03:25 UTC, Ranyar commented on source/index.html
> +      <div class="page-footer__copyright">
Done

2020-11-17 12:00 UTC, Shramkoweb approved these changes

2020-11-17 12:00 UTC, merged