Разметка страницы формы
htmlacademy-adaptive/98669-sedona-21 pull request #3
Opened 2020-11-17 20:54 UTC by Ranyar

2020-11-17 20:58 UTC, Shramkoweb requested changes

2020-11-17 20:58 UTC, Shramkoweb commented on source/form.html
> +              <a href="#">Главная</a>
Это ссылка на главную - главная у нас уже есть))

2020-11-17 20:58 UTC, Shramkoweb commented on source/form.html
> +              <a href="">Форма отзыва</a>
Мы уже на форме. `href=""` надо убрать

2020-11-17 20:58 UTC, Shramkoweb commented on source/form.html
> +          <fieldset class="introduce">
У нас части формы очень похожи.
Инпуты, филдсеты, чекбоксы и радио.

Нужно для всего этого создать общие бем блоки и переиспользовать их.

2020-11-17 20:58 UTC, Shramkoweb commented on source/form.html
> +
??

2020-11-18 10:56 UTC, Ranyar commented on source/form.html
> +
Убрал, это просто для удобства было)

2020-11-18 11:09 UTC, Ranyar commented on source/form.html
> +              <a href="">Форма отзыва</a>
Done

2020-11-18 11:11 UTC, Ranyar commented on source/form.html
> +              <a href="#">Главная</a>
Просмотрел, ночью уже делал) Поправил

2020-11-18 19:29 UTC, Ranyar commented on source/form.html
> +          <fieldset class="introduce">
Done

2020-11-18 19:54 UTC, Shramkoweb approved these changes

2020-11-18 19:54 UTC, merged